name: Build

on: push

jobs:
  build:
    name: Build
    strategy:
      matrix:
        java: [ '8', '11', '17', '19', '20-ea', '21-ea' ]
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - run: ./mvnw clean install -B -V -e -ntp -DtestSecret=${{ secrets.TEST_SECRET }}
