name: OSSRH

on:
  push:
    branches: [ main, master, java ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - run: mvn clean deploy -B -V -e -ntp -DtestSecret=${{ secrets.TEST_SECRET }}
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_USERNAME: albertus82
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
