name: Snapshot

on:
  push:
    branches: '*'
    tags-ignore: v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        server-id: ossrh-snapshot
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - run: mvn clean deploy -B -V -e -ntp -DtestSecret=${{ secrets.TEST_SECRET }}
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
